add icon-classes to align with jenkins way of doing it
fix Java Iterator implementation compile error: does not override abstract method remove()

check for attribute before setting src. Allows svg icon replacement

add icon-size classes like all other jenkins icons have

dispatch browser event someone can subscribe to

remove fix for Favorites.java since it is done by PR #7

fav-icon now set by background and css. Javascript is now i18n aware by jelly wrapper.

Update Favorites.java

remove license information and redundand pom.xml entries. fix whitespace change.

delete unused file

fix whitespace change

fix newline change

icons align vertically now